workflows:
  telegram-ios:
    name: Telegram iOS Build

    instance_type: mac_mini_m2

    environment:
      xcode: 26.2

    scripts:
      - name: Show versions
        script: |
          sw_vers
          xcodebuild -version
          python3 --version

      - name: Prepare project
        script: |
          git submodule update --init --recursive

      - name: Build Telegram
        script: |
          export BAZEL_USER_ROOT=/tmp/bazel

          BUILD_NUMBER_OFFSET=$(cat build_number_offset)

          export APP_VERSION=$(python3 -c "import json;print(json.load(open('versions.json'))['app'])")
          export COMMIT_COUNT=$(git rev-list --count HEAD)
          export BUILD_NUMBER=$((COMMIT_COUNT+BUILD_NUMBER_OFFSET))

          python3 build-system/Make/ImportCertificates.py \
            --path build-system/fake-codesigning/certs

          python3 build-system/Make/Make.py \
            --bazelUserRoot=$BAZEL_USER_ROOT \
            build \
            --configurationPath=build-system/appstore-configuration.json \
            --codesigningInformationPath=build-system/fake-codesigning \
            --configuration=release_arm64 \
            --buildNumber=$BUILD_NUMBER

      - name: Collect IPA
        script: |
          mkdir -p artifacts
          find bazel-out -name "*.ipa" -exec cp {} artifacts/ \;

    artifacts:
      - artifacts/*.ipa
